version: '3'

services:
  mongodb:
    image: mongo
    container_name: bot_db
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
    - ./data:/data/db
    ports:
    - 127.0.0.1:27017:27017
  
  bot:
    image: python:3.12.0b3-slim
    container_name: telegram_bot
    restart: always

